### ISSUE TITLE
Help pls :")

### ISSUE THREAD

**Issue by DGeorgiev26** [AndrewCarterUK/football-predictor#2]
Traceback (most recent call last):
  File "C:\Users\mik.fit\Desktop\football-predictor-master\predict.py", line 3, in <module>
    import tensorflow as tf
ImportError: No module named tensorflow

**Comment by AndrewCarterUK** [comment]
You need to [install TensorFlow](https://www.tensorflow.org/install/).

I'd suggest taking some introductory lessons in Python too, as otherwise you'll struggle to make use of this model.
